#!/bin/bash

while [[ $# -ne 0 ]]; do
  arg=$1
  shift
  case $arg in
    desktop)
      desktop=1
      ;;
  esac
done

dir=$(pwd)
sudo apt update
sudo apt upgrade
cp -r $(cat precious) $HOME/
echo "[[ -f \$HOME/.bashrc.mike ]] && . \$HOME/.bashrc.mike" >> $HOME/.bashrc
sudo groupadd docker
sudo usermod -a -G docker $(id -u -n)
sudo timedatectl set-local-rtc 1

sudo apt install -y git build-essential python3 python3-dev golang clang clang-format cmake make ninja-build nodejs npm vim tmux vim valgrind cproto golang-golang-x-tools net-tools openssh-server docker.io docker-compose htop bear jq cmake-curses-gui ack exuberant-ctags apt-file sqlite3 ncdu wamerican xsel fonts-firacode libelf-dev figlet fzf
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim -c 'VundleInstall' -c 'qa!'
cd $dir
mkdir -p ${HOME}/bin
cp bin/* ${HOME}/bin

cd
mkdir repos
cd repos
git clone https://github.com/neovim/neovim
cd neovim
make && sudo make install
nvim -c ':Lazy install' -c 'qa!'
cd

sudo snap install bw

mkdir secrets
chmod 700 secrets
bw get item "Github PAT" | jq -r .login.password > secrets/github
chmod 600 secrets/github

if [[ -n "$desktop" ]]; then
  sudo apt remove -y ubuntu-web-launchers
  sudo apt install meld fonts-hack-ttf chromium-browser qdirstat kcachegrind zeal
  dconf load / < gsettings
fi

mkdir -p ~/.config/nvim
cp .nvimrc ~/.config/nvim/init.lua
ln -s ~/.config/nvim/init.lua ~/.nvimrc
mkdir -p ~/.local/bin
ln -s ~/bin/cdb2cluster ~/.local/bin/cdb2cluster

cd $HOME
mkdir comdb2
git clone https://github.com/mponomar/comdb2 comdb2/src
cd comdb2
git remote add upstream https://github.com/bloomberg/comdb2
git remote add rivers https://github.com/riverszhang89/comdb2
git remote add akshat https://github.com/akshatsikarwar/comdb2
git remote add nirbhay https://github.com/nirbhayc/comdb2
git remote add dorin https://github.com/dorinhogea/comdb2
git remote add mohit https://github.com/mohitkhullar/comdb2
git remote add mark https://github.com/markhannum/comdb2
sudo apt install -y build-essential cmake bison flex libprotobuf-c-dev libreadline-dev libsqlite3-dev libssl-dev libunwind-dev libevent-dev libz1 libz-dev make gawk protobuf-c-compiler uuid-dev lz4 liblz4-dev libprotobuf-c1 libsqlite3-0 libuuid1 libz1 tzdata ncurses-dev tcl bc
ssh-keygen  -N '' -f ~/.ssh/id_rsa
sudo apt autoremove -y
sudo apt-file update
