#!/bin/bash

dir=$(pwd)
sudo apt update
sudo apt upgrade
sudo apt remove -y firefox ubuntu-web-launchers
cp -r $(cat precious) $HOME/
echo "[[ -f \$HOME/.bashrc.mike ]] && . \$HOME/.bashrc.mike" >> $HOME/.bashrc
sudo usermod -a -G docker $(id -u -n)
sudo timedatectl set-local-rtc 1
apt install -y apt-file bear build-essential chromium-browser clang clang-format cmake cproto ctags docker-compose docker.io fonts-hack-ttf git golang golang-golang-x-tools htop jq k4dirstat make meld net-tools ninja-build nodejs npm openssh-server python3 python3-dev tmux valgrind vim
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim -c 'VundleInstall' -c 'qa!'
cd $HOME/.vim/bundle/YouCompleteMe/
python3 ./install.py --clang-completer --go-completer --js-completer
cd $dir
dconf load / < gsettings
cd $HOME
mkdir comdb2
git clone https://github.com/mponomar/comdb2 comdb2/src
cd comdb2
git remote add upstream https://github.com/bloomberg/comdb2
git remote add adi https://github.com/adizaimi/comdb2
git remote add rivers https://github.com/riverszhang89/comdb2
git remote add mark https://github.com/markhannum/comdb2
git remote add akshat https://github.com/akshatsikarwar/comdb2
git remote add nirbhay https://github.com/nirbhayc/comdb2
git remote add dorin https://github.com/dorinhogea/comdb2
git remote add lingzhi https://github.com/ldennis/comdb2
git remote add mohit https://github.com/mohitkhullar/comdb2
git remote add joe https://github.com/mistachkin/comdb2
git remote add aakash https://github.com/aakash10292/comdb2
git remote add james https://github.com/jmleddy/comdb2
git remote add tim https://github.com/timmui/comdb2
sudo apt install -y build-essential cmake bison flex libprotobuf-c-dev libreadline-dev libsqlite3-dev libssl-dev libunwind-dev libz1 libz-dev make gawk protobuf-c-compiler uuid-dev liblz4-tool liblz4-dev libprotobuf-c1 libsqlite3-0 libuuid1 libz1 tzdata ncurses-dev tcl bc
ssh-keygen  -N '' -f ~/.ssh/id_rsa
sudo apt autoremove -y
sudo apt-file update
